//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPosting()
        {
            this.JobApplieds = new HashSet<JobApplied>();
            this.SelectedCandidates = new HashSet<SelectedCandidate>();
            this.TestResults = new HashSet<TestResult>();
        }
    
        public string JobId { get; set; }
        public string JobDescription { get; set; }
        public string CompanyId { get; set; }
        public string Location { get; set; }
        public System.DateTime PostedDate { get; set; }
        public System.DateTime LastDate { get; set; }
        public bool Status { get; set; }
        public string JobName { get; set; }
        public string JobType { get; set; }
        public Nullable<int> CandidateReq { get; set; }
        public Nullable<int> Salary { get; set; }
    
        public virtual CompanyPortal CompanyPortal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplied> JobApplieds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedCandidate> SelectedCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}
