//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public string QualificationId { get; set; }
        public byte Percentage { get; set; }
        public string ApplicantId { get; set; }
        public System.DateTime YearOfPassing { get; set; }
        public byte Experience { get; set; }
        public string HighestEducation { get; set; }
    
        public virtual JobApplicant JobApplicant { get; set; }
    }
}
