//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rejected
    {
        public string Rejectedid { get; set; }
        public string EmployeeId { get; set; }
        public string CompanyId { get; set; }
        public string CompanyDesc { get; set; }
        public string jobtype { get; set; }
        public Nullable<int> candidatereq { get; set; }
        public string Location { get; set; }
        public string jobName { get; set; }
        public int status { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime LastDate { get; set; }
    
        public virtual CompanyPortal CompanyPortal { get; set; }
        public virtual RecruitmentTeam RecruitmentTeam { get; set; }
    }
}
