//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int TestId { get; set; }
        public string JobId { get; set; }
        public string CandidateId { get; set; }
        public byte Marks { get; set; }
    
        public virtual JobApplicant JobApplicant { get; set; }
        public virtual JobPosting JobPosting { get; set; }
    }
}
