//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestResult()
        {
            this.SelectedCandidates = new HashSet<SelectedCandidate>();
        }
    
        public int TestId { get; set; }
        public string JobId { get; set; }
        public string CandidateId { get; set; }
        public byte Marks { get; set; }
    
        public virtual JobApplicant JobApplicant { get; set; }
        public virtual JobPosting JobPosting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedCandidate> SelectedCandidates { get; set; }
    }
}
